### ISSUE TITLE
SemEval-2010 Task 8 entity type

### ISSUE THREAD

**Issue by zyccyz** [DFKI-NLP/RelEx#1]
Hello, I have used Stanford CoreNLP to get entity type, but it seems that most of the entities cannot be recognized, so I want to know what kind of method did you use?

**Comment by ChristophAlt** [comment]
Hi, thanks for your interest in our work.

I'm not sure whether I understood your question. Are you asking how we obtained the types for the entity-related probing tasks on SemEval?
If that's the case, we obtained the types based on the relation itself, i.e., for a relation "Content-Container" the head entity mention is of type "Content" the tail mention of type "Container". The reason is, as you already observed, that CoreNLP is not particularly suited to annotate SemEval due to its focus on relations between abstract concepts (CONTENT, CONTAINER, etc.) vs. types supported by CoreNLP (ORG, LOC, PER, etc.).

**Comment by zyccyz** [comment]
@ChristophAlt Thank you! 👍
